[package]
name = "derive-mmio-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-error2 = "2.0.1"
proc-macro2 = "1.0.93"
quote = "1.0.38"
rustversion = "1.0.19"
syn = "2.0.98"
